### ISSUE TITLE
能给一个你的静态页面的模板吗  

### ISSUE THREAD

**Issue by feel-easy** [myminwang/myblog#3]
我想着改成前后端分离的那种  想要一个静态的html界面

**Comment by myminwang** [comment]
我没有修改前的页面，你只能自己改下了。。。

**Comment by wasalen** [comment]
可以的 我邮箱[wasalen@foxmail.com]( mailto:wasalen@foxmail.com) 这个是我改了一下css样式之后的  [wasalen](http://www.wangshenglei.top)

**Comment by myminwang** [comment]
抱歉，我是主做后端的，前端了解有限，没看明白你什么意思？
页面在templates里，样式在static里，你直接可以下载的，不知道还需要我给你发什么文件？

**Comment by myminwang** [comment]
这是来自QQ邮箱的自动回复邮件。
             您的邮件我已收到！祝顺~
